server:
  port: 8080

spring:
  application:
    name: bot

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${MEGA_TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
