server:
  port: 8080

spring:
  application:
    name: bot
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094 # ,localhost:9093,localhost:9094
    consumer:
      group-id: groupB

app:
  telegram:
    url: https://api.telegram.org/bot
    scrapperUrl: ${SCRAPPER_URL}
    token: ${MEGA_TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    topic: scrapper-bot
    group: groupB

